### ISSUE TITLE
Windows Build Tray Icon is GitHub Logo

### ISSUE THREAD

**Issue by Akamaozu** [marckohlbrugge/wip-menubar#3]
Great work on creating a native client 👍 

Tiny nitpick: tray icon on windows is not WIP's.

![image](https://user-images.githubusercontent.com/1587024/51337460-2d88e780-1a55-11e9-861a-db2b2ee3ab44.png)

**Comment by Akamaozu** [comment]
@marckohlbrugge should be fixed by https://github.com/marckohlbrugge/wip-menubar/pull/4

**Comment by marckohlbrugge** [comment]
Thank you! Merged.
