### ISSUE TITLE
Suggestion: change the name: "Add New Todo"

### ISSUE THREAD

**Issue by felpsio** [marckohlbrugge/wip-menubar#7]
The first time I read I thought it would add a new pending todo and you had to complete it manually later.

I guess if you replace the name for something like "Complete new Todo" will be more clear since you don't have a option yet to add a "pending todo" through the menubar

**Comment by marckohlbrugge** [comment]
Hey @felpsio just seeing this now!

The input now reads "Press return to complete todo…" and has a checkmark in front of it, so hopefully that's more clear.

If you click the checkmark or type `/todo` it will change to adding a pending todo with the label "Press return to add pending todo…` (You can click the square again, or type `/done` to go back to creating a completed todo).
