### ISSUE TITLE
Can’t find app icon on windows 11

### ISSUE THREAD

**Issue by waptik** [marckohlbrugge/wip-menubar#73]
I downloaded and installed then latest version of the menubar app on win11 but the os couldn’t locate wip.exe. It also tries to open bash.exe
I’m not near my 💻 atm but I’ll send a screenshot later. 

Here's the screenshots of prompts i get after installation
<img width="698" alt="Screenshot 2024-03-07 042844" src="https://github.com/marckohlbrugge/wip-menubar/assets/1687551/47941024-fbda-4ff7-83b4-f73d924a832d">

<img width="773" alt="image" src="https://github.com/marckohlbrugge/wip-menubar/assets/1687551/c926fdaa-14b6-4451-b3c7-e2903da4652a">

**Comment by marckohlbrugge** [comment]
Sorry, but I'm no longer maintaining the app. The amount of work necessary to keep the app working, secure, and available in various app platforms wasn't worth it relative to how few people used the app.

We now have a [Raycast extension](http://raycast.com/marckohlbrugge/wip) which does roughly the same thing. I hope you can use that instead.
