### ISSUE TITLE
Error: Field 'completed_todos_count' doesn't exist on type 'User'

### ISSUE THREAD

**Issue by matthewspear** [marckohlbrugge/wip-menubar#74]
👋 Hey,

I tried getting back into using the WIP menubar app and got this issue:
Error: Field 'completed_todos_count' doesn't exist on type 'User'

Potentially might be linked to API changes mentioned in WIP.

I tried reconnecting my account but didn't solve it, and noticed it said "Welcome undefined" too.

<img width="512" alt="Screenshot 2024-07-18 at 1 45 01 PM" src="https://github.com/user-attachments/assets/faad38f8-9753-4090-90f6-86da4ac6bbd1">
<img width="516" alt="Screenshot 2024-07-18 at 1 45 08 PM" src="https://github.com/user-attachments/assets/aab72833-1596-4801-9980-d00023befb94">

Using Version 2.2.7 on Sonoma 14.5 (23F79), M1 Pro Chip.

**Comment by marckohlbrugge** [comment]
Sorry, but I'm no longer maintaining the app. The amount of work necessary to keep the app working, secure, and available in various app platforms wasn't worth it relative to how few people used the app.

We now have a [Raycast extension](http://raycast.com/marckohlbrugge/wip) which does roughly the same thing. I hope you can use that instead.
